import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...C,"Content-Type":"application/json"}});
const first=(...v:any[])=>v.find(x=>x!==undefined&&x!==null&&x!=="");
const num=(v:any)=>{if(v==null||v==='')return null;const n=Number(String(v).replace(/[^0-9,.-]/g,'').replace(',','.'));return Number.isFinite(n)?n:null};
const priceOf=(o:any)=>num(first(o?.price_eur,o?.price?.value,o?.price));
const idOf=(o:any)=>String(first(o?.id,o?.uuid,o?.offer_id,o?.external_id,''));
const arr=(x:any):any[]=>{if(Array.isArray(x))return x;if(!x||typeof x!=='object')return[];for(const v of[x.data,x.items,x.offers,x.results]){if(Array.isArray(v))return v;if(v&&typeof v==='object'){const a=arr(v);if(a.length)return a}}return[]};
const base=()=> (Deno.env.get('GAMEBOOST_BASE_URL')||'https://api.gameboost.com/v2').replace(/\/$/,'');
async function gb(path:string,method='GET',body?:any){const key=Deno.env.get('GAMEBOOST_API_KEY');if(!key)throw Error('GAMEBOOST_API_KEY belum dikonfigurasi.');const r=await fetch(base()+path,{method,headers:{Authorization:`Bearer ${key}`,Accept:'application/json','Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d:any;try{d=t?JSON.parse(t):null}catch{d={raw:t}}if(!r.ok){const e=new Error(first(d?.message,d?.error,d?.detail,d?.details,`GameBoost HTTP ${r.status}`));(e as any).status=r.status;(e as any).response=d;throw e}return{status:r.status,data:d};}
function offerKind(l:any){const raw=String(first(l?.offer_type,l?.type,l?.metadata?.offer_type,l?.metadata?.type,l?.metadata?.category,'item')).toLowerCase();return raw.includes('currency')?'currency':raw.includes('item')?'item':'unknown';}
async function competing(l:any){if(offerKind(l)!=='currency')return{supported:false,reason:'GameBoost official API documents competing-offer lookup for currency offers, not item offers.'};const r=await gb(`/currency-offers/${encodeURIComponent(String(l.external_offer_id))}/competing-offers`);return{supported:true,offers:arr(r.data)};}
function cheapest(offers:any[],own:string){const a=offers.filter(o=>{const id=idOf(o),p=priceOf(o),s=String(o?.status||'').toLowerCase();return id&&id!==own&&p!=null&&p>0&&!['draft','inactive','unlisted','archived'].includes(s)});a.sort((x,y)=>(priceOf(x)??Infinity)-(priceOf(y)??Infinity));return a[0]||null;}
async function preview(){const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{autoRefreshToken:false,persistSession:false}});const {data:rules,error}=await admin.from('pricing_rules').select('*').eq('enabled',true);if(error)throw error;const {data:listings,error:le}=await admin.from('listings').select('*').in('id',(rules||[]).map((r:any)=>r.listing_id));if(le)throw le;const byId=new Map((listings||[]).map((x:any)=>[x.id,x]));const out:any[]=[];for(const rule of rules||[]){const l=byId.get(rule.listing_id);if(!l?.external_offer_id)continue;try{const own=(await gb(`/item-offers/${encodeURIComponent(l.external_offer_id)}`)).data?.data??(await gb(`/item-offers/${encodeURIComponent(l.external_offer_id)}`)).data;const current=priceOf(own)??Number(l.price||0);const c=await competing(l);if(!c.supported){out.push({listing_id:l.id,offer_id:l.external_offer_id,title:l.title,our_price_eur:current,competitor_price_eur:null,target_price_eur:current,action:'unsupported_offer_type',reason:c.reason});continue;}const co=cheapest(c.offers,String(l.external_offer_id));const cp=co?priceOf(co):null;let target=current,action='no_change',reason='No competitor offer found';if(cp!=null){const under=Math.max(.01,Number(rule.undercut_eur||.1)),desired=Math.max(.01,cp-under),floor=Math.max(rule.min_price_eur==null?0:Number(rule.min_price_eur),rule.max_cut_eur==null?0:current-Number(rule.max_cut_eur));if(desired<current){target=Math.max(desired,floor);action=target<current?'undercut':'floor_protected';reason=`Competitor €${cp.toFixed(2)}; undercut €${under.toFixed(2)}`;}}target=Math.round(target*100)/100;out.push({listing_id:l.id,offer_id:l.external_offer_id,title:l.title,our_price_eur:current,competitor_price_eur:cp,target_price_eur:target,action,reason,competitor_offer_id:co?idOf(co):null});}catch(e){out.push({listing_id:l.id,offer_id:l.external_offer_id,title:l.title,action:'api_error',reason:e instanceof Error?e.message:String(e)});}}return{ok:true,mode:'preview',processed:out.length,previews:out,competitors_source:'GameBoost official API'};}
async function saveRule(req:Request,b:any){const auth=req.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return json({ok:false,error:'Authorization required'},401);const url=Deno.env.get('SUPABASE_URL')!;const uc=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}});const {data:{user},error}=await uc.auth.getUser();if(error||!user)return json({ok:false,error:'Invalid session'},401);const admin=createClient(url,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{autoRefreshToken:false,persistSession:false}});const p:any={user_id:user.id,listing_id:b.listing_id,enabled:Boolean(b.enabled),undercut_eur:Math.max(.01,Number(b.undercut_eur||.1)),min_price_eur:b.min_price_eur==null?null:Number(b.min_price_eur),max_cut_eur:b.max_cut_eur==null?null:Number(b.max_cut_eur),follow_up_enabled:Boolean(b.follow_up_enabled),follow_up_raise_eur:Math.max(0,Number(b.follow_up_raise_eur||0)),follow_up_max_price_eur:b.follow_up_max_price_eur==null?null:Number(b.follow_up_max_price_eur),interval_minutes:Math.max(5,Math.min(60,Math.trunc(Number(b.interval_minutes||15))))};const q=await admin.from('pricing_rules').upsert(p,{onConflict:'user_id,listing_id'}).select('*').single();if(q.error)throw q.error;return json({ok:true,rule:q.data});}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});try{let b:any={};try{b=await req.json()}catch{}if(b.operation==='save_rule')return await saveRule(req,b);if(b.operation==='preview')return json(await preview());return json({ok:false,error:'Unsupported operation'},400);}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500);}});