import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// Competitive pricing worker. It reads pricing_rules, compares matching GameBoost offers,
// applies safety floors/caps, updates the remote offer, verifies the result, and records history.
const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...C,"Content-Type":"application/json"}});
const first=(...v:any[])=>v.find(x=>x!==undefined&&x!==null&&x!=="");
const num=(v:any)=>{if(v==null||v==='')return null;const x=Number(String(v).replace(/[^0-9,.-]/g,'').replace(',','.'));return Number.isFinite(x)?x:null};
const priceOf=(o:any)=>num(first(o?.price_eur,o?.price,o?.price?.value));
const arr=(x:any):any[]=>{if(Array.isArray(x))return x;if(!x||typeof x!=='object')return[];for(const v of[x.data,x.items,x.offers,x.results]){if(Array.isArray(v))return v;if(v&&typeof v==='object'){const a=arr(v);if(a.length)return a}}return[]};
const norm=(x:any)=>String(x??'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const base=()=> (Deno.env.get('GAMEBOOST_BASE_URL')||'https://api.gameboost.com/v2').replace(/\/$/,'');
async function gb(path:string,method='GET',body?:any){const key=Deno.env.get('GAMEBOOST_API_KEY');if(!key)throw Error('GAMEBOOST_API_KEY belum dikonfigurasi.');const r=await fetch(base()+path,{method,headers:{Authorization:`Bearer ${key}`,Accept:'application/json','Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d:any;try{d=t?JSON.parse(t):null}catch{d={raw:t}}if(!r.ok){const e=new Error(first(d?.message,d?.error,d?.detail,d?.details,`GameBoost HTTP ${r.status}`));(e as any).status=r.status;(e as any).response=d;throw e}return{status:r.status,data:d};}
async function allOffers(){const out:any[]=[];for(let page=1;page<=20;page++){const r=await gb(`/item-offers?per_page=100&page=${page}&sort=price`);const a=arr(r.data);out.push(...a);if(a.length<100)break;}return out;}
function offerTitle(o:any){return String(first(o?.title,o?.product_name,o?.name,''));}
function offerGame(o:any){return norm(first(o?.game?.slug,o?.game?.name,o?.game_slug,o?.game_name,o?.game,''));}
function competitorFor(target:any,offers:any[]){const own=String(target.external_offer_id);const title=norm(target.title);const game=norm(first(target.metadata?.game?.slug,target.metadata?.game_slug,target.metadata?.game_name,target.metadata?.game,''));const candidates=offers.filter(o=>{const id=String(first(o?.id,o?.uuid,o?.offer_id,o?.external_id,''));if(!id||id===own)return false;const s=norm(offerTitle(o));const g=offerGame(o);const p=priceOf(o);const st=String(o?.status||'').toLowerCase();if(!title||!s||p==null||p<=0||['draft','inactive','unlisted','archived'].includes(st))return false;const titleMatch=s===title||s.includes(title)||title.includes(s);const gameMatch=!game||!g||g===game||g.includes(game)||game.includes(g);return titleMatch&&gameMatch;});candidates.sort((a,b)=>(priceOf(a)??Infinity)-(priceOf(b)??Infinity));return candidates[0]||null;}
async function run(){const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{autoRefreshToken:false,persistSession:false}});const {data:rules,error}=await admin.from('pricing_rules').select('*').eq('enabled',true);if(error)throw error;if(!rules?.length)return{ok:true,processed:0,changed:0,skipped:0};const {data:listings,error:le}=await admin.from('listings').select('*').in('id',rules.map((r:any)=>r.listing_id));if(le)throw le;const byId=new Map((listings||[]).map((x:any)=>[x.id,x]));const offers=await allOffers();let changed=0,skipped=0,processed=0;const errors:any[]=[];
for(const rule of rules){processed++;const listing=byId.get(rule.listing_id);if(!listing||!listing.external_offer_id){skipped++;continue;}try{const current=await gb(`/item-offers/${encodeURIComponent(listing.external_offer_id)}`);const remote=current.data?.data??current.data;const currentPrice=priceOf(remote)??Number(listing.price||0);const competitor=competitorFor(listing,offers);const cp=competitor?priceOf(competitor):null;let target:number|null=null;let action='no_change';let reason='No competitor price found';if(cp!=null){const under=Math.max(0.01,Number(rule.undercut_eur||0.1));const undercutTarget=Math.max(0.01,cp-under);const floor=rule.min_price_eur==null?0:Number(rule.min_price_eur);const maxCut=rule.max_cut_eur==null?Infinity:Number(rule.max_cut_eur);const cutFloor=Math.max(floor,currentPrice-maxCut);if(undercutTarget<currentPrice){target=Math.max(undercutTarget,cutFloor);action=target<currentPrice?'undercut':'floor_protected';reason=`Competitor €${cp.toFixed(2)}; undercut €${under.toFixed(2)}`;}else if(rule.follow_up_enabled&&undercutTarget>currentPrice){const maxFollow=rule.follow_up_max_price_eur==null?Infinity:Number(rule.follow_up_max_price_eur);const raise=Number(rule.follow_up_raise_eur||0);target=Math.min(undercutTarget,raise>0?currentPrice+raise:undercutTarget,maxFollow);if(target>currentPrice){action='follow_up';reason=`Competitor naik ke €${cp.toFixed(2)}; follow-up menuju €${undercutTarget.toFixed(2)}`;}}
if(target!=null&&Math.abs(target-currentPrice)>0.004){target=Math.round(target*100)/100;await gb(`/item-offers/${encodeURIComponent(listing.external_offer_id)}`,'PATCH',{price:target});const verify=await gb(`/item-offers/${encodeURIComponent(listing.external_offer_id)}`);const verified=priceOf(verify.data?.data??verify.data);if(verified==null||Math.abs(verified-target)>0.005)throw Error(`Price verification failed: expected ${target}, got ${verified}`);await admin.from('listings').update({price:target,updated_at:new Date().toISOString()}).eq('id',listing.id);await admin.from('pricing_history').insert({user_id:rule.user_id,listing_id:listing.id,offer_id:listing.external_offer_id,old_price_eur:currentPrice,competitor_price_eur:cp,new_price_eur:target,action,reason});changed++;}else{skipped++;await admin.from('pricing_history').insert({user_id:rule.user_id,listing_id:listing.id,offer_id:listing.external_offer_id,old_price_eur:currentPrice,competitor_price_eur:cp,new_price_eur:currentPrice,action:'no_change',reason});}}catch(e){skipped++;if(errors.length<20)errors.push({listing_id:listing.id,offer_id:listing.external_offer_id,error:e instanceof Error?e.message:String(e)});}}
return{ok:errors.length===0,processed,changed,skipped,errors,competitors_source:'GameBoost item-offers API'};}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});try{let body:any={};try{body=await req.json();}catch{}if(body.operation==='save_rule'){const auth=req.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return json({ok:false,error:'Authorization required'},401);const url=Deno.env.get('SUPABASE_URL')!;const userClient=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}});const {data:{user},error}=await userClient.auth.getUser();if(error||!user)return json({ok:false,error:'Invalid session'},401);const admin=createClient(url,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{autoRefreshToken:false,persistSession:false}});const p:any={user_id:user.id,listing_id:body.listing_id,enabled:Boolean(body.enabled),undercut_eur:Math.max(0.01,Number(body.undercut_eur||0.1)),min_price_eur:body.min_price_eur==null?null:Number(body.min_price_eur),max_cut_eur:body.max_cut_eur==null?null:Number(body.max_cut_eur),follow_up_enabled:Boolean(body.follow_up_enabled),follow_up_raise_eur:Math.max(0,Number(body.follow_up_raise_eur||0)),follow_up_max_price_eur:body.follow_up_max_price_eur==null?null:Number(body.follow_up_max_price_eur),interval_minutes:Math.max(5,Math.min(60,Math.trunc(Number(body.interval_minutes||15))))};const q=await admin.from('pricing_rules').upsert(p,{onConflict:'user_id,listing_id'}).select('*').single();if(q.error)throw q.error;return json({ok:true,rule:q.data});}if(body.operation==='run'||!body.operation)return json(await run());return json({ok:false,error:'Unsupported operation'},400);}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500);}});
