import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(x:unknown,status=200)=>new Response(JSON.stringify(x),{status,headers:{...C,"Content-Type":"application/json"}});
const first=(...v:any[])=>v.find(x=>x!==undefined&&x!==null&&x!=="");
const num=(v:any):number|null=>{if(v==null||v==="")return null;if(typeof v==="object")return num(first(v.value,v.amount!=null?Number(v.amount)/100:null));const n=Number(String(v).replace(/[^0-9,.-]/g,"").replace(",","."));return Number.isFinite(n)?n:null};
const norm=(v:any)=>String(v??"").toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
const slug=(v:any)=>norm(v).replace(/\s+/g,"-");
function extractInertia(html:string):any{const candidates:string[]=[];const re=/<script[^>]*type=["']application\/json["'][^>]*>([\s\S]*?)<\/script>/gi;for(const m of html.matchAll(re))candidates.push(m[1]);const attrs=html.match(/data-page=["'][^"']+["']/gi)||[];for(const x of attrs){const m=x.match(/data-page=["']([^"']+)["']/i);if(m)candidates.push(m[1].replace(/&quot;/g,'"').replace(/&#39;/g,"'"))}for(const body of candidates){try{const p=JSON.parse(body);if(Array.isArray(p?.props?.items?.data))return p}catch{}}return null}
function normalizeListing(item:any,locale:string,game:string){const price=item?.price?.value??num(item?.price),localPrice=item?.local_price?.value??num(item?.local_price),seller=item?.seller||{};return{id:item?.id??null,title:item?.title??"",slug:item?.slug??"",seller:seller?.username??null,seller_id:seller?.id??null,seller_verified:seller?.is_verified??false,seller_rating:seller?.rating?.value??null,seller_orders:seller?.total_sales??null,seller_ratings:seller?.total_ratings??null,price,currency:item?.price?.currency?.code??"EUR",price_format:item?.price?.format??null,local_price:localPrice,local_currency:item?.local_price?.currency?.code??"USD",local_price_format:item?.local_price?.format??null,stock:item?.stock??null,min_quantity:item?.min_quantity??null,delivery_time:item?.delivery_time??null,status:item?.status??null,item_type:item?.data?.item_type??null,image_url:item?.icon_url??item?.media?.[0]??null,updated_at:item?.updated_at??null,created_at:item?.created_at??null,url:item?.slug?`https://gameboost.com/${locale}/${game}/items/${item.slug}`:null}}
async function fetchPublicListings(game:string,search:string,locale="id",page=1,sort="price"){if(!game)throw Error("Game slug wajib diisi.");if(!search)throw Error("Search item wajib diisi.");const u=new URL(`https://gameboost.com/${locale}/${game}/items`);u.searchParams.set("s",search);u.searchParams.set("sort",sort);u.searchParams.set("page",String(Math.max(1,page)));const response=await fetch(u.toString(),{headers:{Accept:"application/json, text/plain, */*", "X-Inertia":"true", "X-Requested-With":"XMLHttpRequest", "X-Inertia-Version":"3df20cadddcb1d19c1c1acddc1335ef3", "Accept-Language":locale==="id"?"id-ID,id;q=0.9,en;q=0.7":"en-US,en;q=0.9", Referer:`https://gameboost.com/${locale}/${game}/items`, Origin:"https://gameboost.com", "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/131.0.0.0 Safari/537.36"}});const html=await response.text();if(!response.ok)throw Error(`GameBoost Inertia HTTP ${response.status}`);const inertia=extractInertia(html);if(!inertia)throw Error(`Payload Inertia GameBoost tidak ditemukan (HTTP ${response.status}, ${html.length} bytes).`);const items=inertia.props.items||{},raw=Array.isArray(items.data)?items.data:[],listings=raw.map((x:any)=>normalizeListing(x,locale,game));return{component:inertia.component??null,query:items.query??null,path:items.path??u.toString(),current_page:items.current_page??page,per_page:items.per_page??listings.length,total:items.total??null,last_page:items.last_page??null,next_page_url:items.next_page_url??null,prev_page_url:items.prev_page_url??null,listings,source_url:u.toString()}}
async function auth(req:Request){const h=req.headers.get("Authorization");if(!h?.startsWith("Bearer "))throw Object.assign(Error("Authorization required"),{status:401});const url=Deno.env.get("SUPABASE_URL")!,client=createClient(url,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:h}}});const{data:{user},error}=await client.auth.getUser();if(error||!user)throw Object.assign(Error("Invalid session"),{status:401});return{user,admin:createClient(url,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{autoRefreshToken:false,persistSession:false}})}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:C});if(req.method!=="POST")return json({ok:false,error:"POST only"},405);try{const body=await req.json().catch(()=>({}));if(body?.operation==="search"){try{return json({ok:true,...await fetchPublicListings(slug(body?.game),String(body?.search||"").trim(),String(body?.locale||"id"),Number(body?.page||1),String(body?.sort||"price"))})}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e),operation:"search"},200)}}const{user,admin}=await auth(req);return json({ok:true,mode:"preview",read_only:true,processed:0,previews:[],user_id:user.id,admin_ready:!!admin})}catch(error){const status=(error as any)?.status;return json({ok:false,error:error instanceof Error?error.message:String(error)},status===401?401:500)}});
