import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...C,"Content-Type":"application/json"}});
const base=()=> (Deno.env.get('GAMEBOOST_BASE_URL')||'https://api.gameboost.com/v2').replace(/\/$/,'');
async function gb(path:string,method='GET'){const key=Deno.env.get('GAMEBOOST_API_KEY');if(!key)throw Error('GAMEBOOST_API_KEY belum dikonfigurasi.');const r=await fetch(base()+path,{method,headers:{Authorization:`Bearer ${key}`,Accept:'application/json','Content-Type':'application/json'}});const t=await r.text();let d:any;try{d=t?JSON.parse(t):null}catch{d={raw:t}}if(!r.ok)throw Object.assign(Error(d?.message||d?.error||`GameBoost HTTP ${r.status}`),{status:r.status,details:d});return{status:r.status,data:d}}
async function auth(req:Request){const h=req.headers.get('Authorization');if(!h?.startsWith('Bearer '))throw Object.assign(Error('Missing authorization'),{status:401});const url=Deno.env.get('SUPABASE_URL')!;const c=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:h}}});const {data:{user},error}=await c.auth.getUser();if(error||!user)throw Object.assign(Error('Invalid or expired session'),{status:401});return user}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:C});if(req.method!=='POST')return json({ok:false,error:'POST only'},405);try{await auth(req);let body:any={};try{body=await req.json()}catch{}const id=String(body?.offer_id||body?.external_offer_id||'').trim();if(!id)return json({ok:false,error:'offer_id wajib diisi'},400);const archived=await gb(`/item-offers/${encodeURIComponent(id)}/archive`,'POST');let verified:any=null;try{verified=await gb(`/item-offers/${encodeURIComponent(id)}`,'GET')}catch(e){verified={error:e instanceof Error?e.message:String(e)}}const offer=verified?.data?.data??verified?.data??archived.data?.data??archived.data?.offer??archived.data;const status=String(offer?.status??archived.data?.status??archived.data?.data?.status??'').toLowerCase();if(['active','listed'].includes(status))return json({ok:false,error:'GameBoost menerima archive tetapi offer masih aktif.',gameboost_status:archived.status,verified_status:status,offer},502);return json({ok:true,gameboost_status:archived.status,verified:true,verified_status:status||null,offer,message:archived.data?.message??null})}catch(e){const s=(e as any)?.status;return json({ok:false,error:e instanceof Error?e.message:String(e),details:(e as any)?.details??null},s===401?401:502)}});
